version: '3.5'
services:
  valorant-watcher:
    #build: . #For local build
    #image: valorant-watcher:latest #For local build
    image: d3vm/valorant-watcher:latest
    restart: always
    environment:
      - token=eq6jfv87752fd8xdxcnxxzlmipgd71 #Example value from readme
      #- streamersUrl=https://www.twitch.tv/directory/game/Rust?sort=VIEWER_COUNT&tl=c2542d6d-cd10-4532-919b-3d19f30a768b
      #- watchAlwaysTopStreamer=true
      #- channelsWithPriority=illojuan,alexby11,aroyitt
      #- userAgent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
      #- scrollDelay=2000
      #- scrollTimes=5
      #- minWatching=6
      #- maxWatching=15
      #- streamerListRefres=2
      #- streamerListRefreshUnit=hour
      #- browserScreenshot=false
      #- proxy=ip:port
      #- proxyAuth=username:password
    #volumes:
    #  - "./screenshots:/usr/src/app/screenshots"
